# Generated by Django 4.1.3 on 2023-03-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orginal_news', models.TextField(blank=True, default='', null=True)),
                ('converted_news', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
